### ISSUE TITLE
Q: Why doesn't unpredictableSeed() query the OS APIs for random data?

### ISSUE THREAD

**Issue by wilzbach** [libmir/mir-random#11]
`unpredictableSeed` uses the time and process id to generate a random seed (see [here](https://github.com/libmir/mir-random/blob/master/source/mir/random/engine/package.d#L69)).

Q: Why doesn't it let the OS do the work? (e.g. `/dev/random` or [`getrandom`](https://github.com/libmir/mir-random/issues/10))

(comes from Dlang's issue tracker: https://issues.dlang.org/show_bug.cgi?id=16493)

**Comment by 9il** [comment]
No reason. PRs are highly welcome!
