### ISSUE TITLE
What is the current strategy to handle wrong input?

### ISSUE THREAD

**Issue by drug007** [libmir/mir-random#122]
In [ndvariable](https://github.com/libmir/mir-random/blob/9c711d2a88e097d1cc3f07b384c51b2acd89b58e/source/mir/random/ndvariable.d#L471) `assert` is used to signal about wrong input. But `assert` is not convenient very much 'cause it's too fatal. Cannot exceptions be used here?

**Comment by 9il** [comment]
The `nothrow` option should be preserved by default. Exceptions can be thrown for an additionally defined version.

**Comment by drug007** [comment]
I see. Should I close the issue or leave it as is as some kind of docs?
