### ISSUE TITLE
Random generation of integers

### ISSUE THREAD

**Issue by tastyminerals** [libmir/mir-random#128]
I struggle to find how to do a simple random integer generation.

```d
import mir.random;
import mir.random.engine.mersenne_twister;
void main() {
    auto rng = Mt19937(123);
    auto n = rng.rand!int(10);
}
```
does not work.
So, whenever I want to generate a random integer I'd have to `cast`. Is there a Mir alternative to `np.random.randint(1, 10)`?

**Comment by jmh530** [comment]
You can use [UniformVariable](http://mir-random.libmir.org/mir_random_variable.html#UniformVariable).

**Comment by tastyminerals** [comment]
Yep, just found it and also looks like `randIndex` is what I need.
