### ISSUE TITLE
MersenneTwisterEngine does not support non-standard word sizes

### ISSUE THREAD

**Issue by WebDrake** [libmir/mir-random#15]
The `MersenneTwisterEngine` template distinguishes between the `UIntType` used to store generator state, and the word size `w`: for example, when `UIntType` is `ulong` (64-bit), the word size may still be only 32 or (say) 48 bits.  In this case the returned variates should consist of only the lowest `w` bits of the generated `UIntType` value (which is not currently enforced) and the seeding process should also take this into account (currently only partially done: the first entry in the state array takes the lowest `w` bits of the provided seed, but the population of the other state array entries does not take this into account).

Comparison of output of `mir.random`'s `MersenneTwisterEngine` and C++11's `mersenne_twister_engine` can be made using the following D unittest:

```D
unittest
{
    alias MT(UIntType, uint w) = MersenneTwisterEngine!(UIntType, w, 624, 397, 31,
                                                        0x9908b0df, 11, 0xffffffff, 7,
                                                        0x9d2c5680, 15,
                                                        0xefc60000, 18, 1812433253);

    foreach (R; std.meta.AliasSeq!(MT!(uint, 32), MT!(ulong, 32), MT!(ulong, 48), MT!(ulong, 64)))
    {
        static if (R.wordSize == 48) static assert(R.max == 0xFFFFFFFFFFFF);
        auto a = R(R.defaultSeed);
        import std.stdio : writeln;
        writeln(a());
        writeln(a());
        writeln();
    }
}
```

... and the following C++11 program:

```C++
#include <cinttypes>
#include <iostream>
#include <random>
#include <type_traits>

template<class UIntType, size_t w>
void mt_result ()
{
    std::mersenne_twister_engine<
        UIntType, w, 624, 397, 31,
        0x9908b0df, 11, 0xffffffff, 7,
        0x9d2c5680, 15,
        0xefc60000, 18, 1812433253> gen;

    gen.seed(std::mt19937::default_seed);
    std::cout << gen() << std::endl;
    //for (int i = 0; i < 599; ++i)
    //  gen();
    std::cout << gen() << std::endl;
    std::cout << std::endl;
}

int main ()
{
    mt_result<uint32_t, 32>();
    mt_result<uint64_t, 32>();
    mt_result<uint64_t, 48>();
    mt_result<uint64_t, 64>();
}
```

**Comment by WebDrake** [comment]
Running on my current Ubuntu 16.04 system, compiling the D code with LDC v1.1.0-beta6 and the C++ with g++ 5.4.0, I get the following output:

From D:
```
3499211612
581869302

3752444003632941981
9913009752712247639

10303168874589063625
10293149814823965613

1145028863177033374
13274043268593078489
```

From C++:
```
3499211612
581869302

3499211612
581869302

171143175841277
69489540040343

1145028863177033374
13274043268593078489
```

**Comment by 9il** [comment]
Does Phobos has the same issue?

**Comment by WebDrake** [comment]
Now, some notes.  If we compare with the pseudocode available at:
https://en.wikipedia.org/wiki/Mersenne_Twister#Pseudocode

we see there are several places where the word size `w` is taken into account:

* when creating the `upperMask` (which AFAICT is done in `mir.random`, but might be worth re-checking);

* when seeding (not done, except for the very first seed value);

* when returning the tempered variate (not done).

I've tried fixing these points using the following patch:

```diff
diff --git a/source/mir/random/engine/mersenne_twister.d b/source/mir/random/engine/mersenne_twister.d
index bb6a4b4..de757bf 100644
--- a/source/mir/random/engine/mersenne_twister.d
+++ b/source/mir/random/engine/mersenne_twister.d
@@ -33,6 +33,8 @@ struct MersenneTwisterEngine(UIntType, size_t w, size_t n, size_t m, size_t r,
     private enum UIntType upperMask = ~((cast(UIntType) 1u << (UIntType.sizeof * 8 - (w - r))) - 1);
     private enum UIntType lowerMask = (cast(UIntType) 1u << r) - 1;
 
+    private enum wordSizeMask = UIntType.max >> (UIntType.sizeof * 8 - w);
+
     /**
     Parameters for the generator.
     */
@@ -79,10 +81,16 @@ struct MersenneTwisterEngine(UIntType, size_t w, size_t n, size_t m, size_t r,
         else
         {
             static assert(max + 1 > 0);
-            data[$-1] = value % (max + 1);
+            data[$-1] = value & wordSizeMask;
         }
         foreach_reverse (size_t i, ref e; data[0 .. $-1])
+        {
             e = f * (data[i + 1] ^ (data[i + 1] >> (w - 2))) + cast(UIntType)(n - (i + 1));
+            static if (w != UIntType.sizeof * 8)
+            {
+                e &= wordSizeMask;
+            }
+        }
         index = n-1;
         opCall();
     }
@@ -128,7 +136,15 @@ struct MersenneTwisterEngine(UIntType, size_t w, size_t n, size_t m, size_t r,
         z ^= (z >> l);
         _z = data[index] = e;
         this.index = cast(UIntType)next;
-        return z;
+
+        static if (w == UIntType.sizeof * 8)
+        {
+            return z;
+        }
+        else
+        {
+            return z & wordSizeMask;
+        }
     }
 }
 
@@ -194,3 +210,21 @@ else
         gen64();
     assert(gen64() == 9981545732273789042uL);
 }
+
+unittest
+{
+    alias MT(UIntType, uint w) = MersenneTwisterEngine!(UIntType, w, 624, 397, 31,
+                                                        0x9908b0df, 11, 0xffffffff, 7,
+                                                        0x9d2c5680, 15,
+                                                        0xefc60000, 18, 1812433253);
+
+    foreach (R; std.meta.AliasSeq!(MT!(uint, 32), MT!(ulong, 32), MT!(ulong, 48), MT!(ulong, 64)))
+    {
+        static if (R.wordSize == 48) static assert(R.max == 0xFFFFFFFFFFFF);
+        auto a = R(R.defaultSeed);
+        import std.stdio : writeln;
+        writeln(a());
+        writeln(a());
+        writeln();
+    }
+}
```

... and these changes result in the following output:

```
3499211612
581869302

3499211612
581869302

171143175841277
65652244619943

1145028863177033374
13274043268593078489
```

... i.e. for word size 32 things now seem to match, but for word size 48 while the _first_ variate matches, the second doesn't.  This makes me suspect that `opCall` is now rendered correct with the above changes, but that there is still a difference in the seeding mechanism (in terms of all but the first assigned entry of the `data` array) which prevents the second variate from being handled correctly.

**Comment by WebDrake** [comment]
> Does Phobos have the same issue?

Comparison to original phobos is not readily possible, because it's in any case missing several of the template parameters of concern.  I could try things out with `hap.random` (which brought in the missing parameters) but that is almost certainly also missing the word-size related concerns.  I'll confirm, though.

**Comment by WebDrake** [comment]
Note, the introduction of the `wordSizeMask` in my suggested patch above is not strictly necessary; taking `value % (max + 1)` is perfectly good enough and produces the same results.

**Comment by WebDrake** [comment]
Hmmm, interesting!  `hap.random` matches C++11 in its behaviour.  If I recall right this was based on a contemporary `Boost.Random` implementation (which frustratingly enough I don't think is documented; I should patch the documentation accordingly...).

You can check out the code here: https://github.com/WebDrake/hap

... and IIRC the boost libraries still include `Boost.Random` although I think it is not longer publicly documented, so this can also be a point of comparison.

Example unittest for `hap.random`:

```D
unittest
{
    alias MT(UIntType, uint w) = MersenneTwisterEngine!(UIntType, w, 624, 397, 31,
                                                        0x9908b0df, 11, 0xffffffff, 7,
                                                        0x9d2c5680, 15,
                                                        0xefc60000, 18, 1812433253);

    foreach (R; std.meta.AliasSeq!(MT!(uint, 32), MT!(ulong, 32), MT!(ulong, 48), MT!(ulong, 64)))
    {
        static if (R.wordSize == 48) static assert(R.max == 0xFFFFFFFFFFFF);
        auto a = new R(R.defaultSeed);
        import std.stdio : writeln;
        writeln(a.front);
        a.popFront/*N(600)*/;
        writeln(a.front);
        writeln();
    }
}
```

**Comment by 9il** [comment]
Found the bug fix. Fill create a PR soon
