### ISSUE TITLE
Do not dual-purpose meaning of `Mt19937` name

### ISSUE THREAD

**Issue by WebDrake** [libmir/mir-random#19]
`mir.random` currently uses the name `Mt19937` to mean the standard 32-bit generator when building for 32-bit targets and the MT19937-64 generator when building for 64-bit targets.

However, this is problematic terminology.  MT19937 is explicitly defined to be the version of the generator that has a 32-bit unsigned integer as its data type, a 32-bit word size, a 624-word state, etc. etc.: see the opening paragraphs of https://en.wikipedia.org/wiki/Mersenne_Twister

The recommended course of action here is to delete the `Mt19937_32` symbol and to use `Mt19937` as the symbol only for the 32-bit generator.  If this is acceptable I'll submit patches to this effect.

Note the changes proposed here do not affect the decision of what the default RNG `Random` should be.

**Comment by 9il** [comment]
How C++ solves this issue?

**Comment by WebDrake** [comment]
See the `Template instantiations` section of the following:
http://www.cplusplus.com/reference/random/mersenne_twister_engine/

In C++11 `mt19937` is the 32-bit version and `mt19937_64` is the 64-bit version.

**Comment by 9il** [comment]
agreed

**Comment by WebDrake** [comment]
OK, patch on its way soon.

**Comment by 9il** [comment]
Thanks!

**Comment by WebDrake** [comment]
OK, one challenge for this: `unpredictableSeed` returns `size_t` which means it is problematic (on 64-bit systems) for seeding a 32-bit Mersenne Twister.  How would you prefer this to be handled?

My own inclination is that there should be both 32- and 64-bit implementations of `unpredictableSeed` available.

**Comment by 9il** [comment]
just `cast(uint)`
