### ISSUE TITLE
http://docs.random.dlang.io/ does not work

### ISSUE THREAD

**Issue by 9il** [libmir/mir-random#2]

**Comment by thewilsonator** [comment]
Works for me. What's wrong?

**Comment by 9il** [comment]
http://docs.random.dlang.io/ - `Hello` word
http://docs.random.dlang.io/latest/index.html - works

**Comment by wilzbach** [comment]
Added a simple redirect from http://docs.random.dlang.io to `/latest` ;-)

**Comment by 9il** [comment]
Thanks!
