### ISSUE TITLE
Latest release 0.2.5 does not include PCG?

### ISSUE THREAD

**Issue by mlabayru** [libmir/mir-random#25]
I can't find pcg.d inside zip for release 0.2.5...

**Comment by thewilsonator** [comment]
should be under `mir/random/engine/pcg.d`.

**Comment by mlabayru** [comment]
There is no pcg.d in that route inside mir-random-0.2.5.zip.
mir/random/engine only contains these files:
linear_congruential.d
mersenne_twister.d
package.d
xorshift.d

**Comment by 9il** [comment]
Oh, my bad. Will create a new tag soon

**Comment by thewilsonator** [comment]
Hmm https://github.com/libmir/mir-random/compare/v0.2.5...master shows that #1 was merged after 0.2.5 was tagged. @9il did you tag the wrong commit?

**Comment by 9il** [comment]
Tagged in `v0.2.6`, dub registry will be auto updated during 30 mins.

**Comment by 9il** [comment]
thanks @mlabayru
