### ISSUE TITLE
Proposal: xorshift1024*φ as the default Random on 64-bit systems

### ISSUE THREAD

**Issue by n8sh** [libmir/mir-random#30]
`xorshift1024*` / `xorshift1024*φ` is [faster and has better statistical properties](http://xoroshiro.di.unimi.it/#quality) than `Mt19937_94` while occupying considerably less memory (136 bytes vs 2512 bytes).

I might suggest that the default `mir.random.engine.Random` should be something much more lightweight, but using `xorshift1024*` will not harm any existing code that assumes that `Random` is suitable for massive simulations. Rather, such code will be improved.

I have made a branch with the proposed change:
https://github.com/n8sh/mir-random/commit/7dc9438f1a22fdc3f06df611ab202bf911646526

**Comment by 9il** [comment]
Definitely we should add this Xorshift generators. Please  open a PR. 

The default rng is another question  The default engine must not be less cryptographically and statistically stronger then MT, speed is matter but has less priority comparing with cryptography.

**Comment by 9il** [comment]
Anyway, community should test it for a while before make it default.
