### ISSUE TITLE
Check that all Saturated RNGs are safe and the trait and mark all other functions as safe

### ISSUE THREAD

**Issue by 9il** [libmir/mir-random#42]

**Comment by n8sh** [comment]
Most mir.random functions are generic and automatically infer `@safe`-ty. I think the generators we include in mir.random.engines should be `@safe` (and `pure` and `nothrow` and `@nogc`), but I do not believe there is a need to limit the users from defining non-`@safe` generators and using them with this library.

**Comment by n8sh** [comment]
One example of a function that currently doesn't preserve `@safe`ty, however, is `rand!(T,G)` when  `isIntegral!T` and `T.sizeof > EngineReturnType!G.sizeof`.

[But we can fix this with:](https://github.com/libmir/mir-random/pull/39/commits/2e90600bd905d71653a0735058b296fbe1061222)
```
        static if (is(typeof((ref G g) @safe => g())))
        {
            return () @trusted {
            T ret = void;
            foreach(p; 0..P)
                (cast(R*)(&ret))[p] = gen();
            return ret;
                }();
        }
        else
        {
            T ret = void;
            foreach(p; 0..P)
                (cast(R*)(&ret))[p] = gen();
            return ret;
        }
```

**Comment by 9il** [comment]
The problem that is _very_ significantly makes safety testing complex.
`T ret = void;` is not safe for example. It is not a big problem for user to make their RNGs safe, but it allows us to provide safe API without headache. It is workforce optimisation question.

**Comment by 9il** [comment]
> Most mir.random functions are generic and automatically infer @safe-ty.

This should be covered in unittests for _each_ function :-/
