### ISSUE TITLE
mir-random does not compile with latest ldc on raspberry pi

### ISSUE THREAD

**Issue by 9il** [libmir/mir-random#49]
original https://github.com/libmir/mir/issues/390

**Comment by 9il** [comment]
@gizmomogwai could you please specify OS/kernel version?

**Comment by gizmomogwai** [comment]
kernel:
> uname -a
Linux wohnzimmer 4.9.29-10-osmc #1 SMP PREEMPT Mon Oct 9 02:18:18 UTC 2017 armv7l GNU/Linux

this is osmc distribution for raspberry pi 2 (running on rpi 3).

**Comment by n8sh** [comment]
The problem is this:

```
version(linux)
{
//...
    version (X86_64)
        private enum GETRANDOM = 318;
    version (X86)
        private enum GETRANDOM = 355;
//...
```

Since `GETRANDOM` is not defined for other architectures, the outer condition should check architecture instead of just OS.
