### ISSUE TITLE
this._z is used uninitialized in MersenneTwisterEngine.opCall

### ISSUE THREAD

**Issue by WebDrake** [libmir/mir-random#6]
The `_z` field of the `MersenneTwisterEngine` is uninitialized on struct creation:
https://github.com/libmir/mir-random/blob/b518dbb95fbe004f1b235295450522b2f0f49465/source/mir/random/engine/mersenne_twister.d#L107

The constructor does not touch it directly, but calls `popFront()`, where in this first call, `_z` is used to set the value of `z` without `_z` itself having been initialized first:
https://github.com/libmir/mir-random/blob/b518dbb95fbe004f1b235295450522b2f0f49465/source/mir/random/engine/mersenne_twister.d#L153

Presumably the intention/expectation is that `_z` should be initialized to `data[index]` in the constructor?

**Comment by WebDrake** [comment]
Note that the effect is unobservable because the variate generated is never used (`opCall` is called from the constructor without its return value being used, and at the end of that `opCall` `_z` is set to a sane value).  However, this should arguably be fixed, since it's technically undefined behaviour.

**Comment by WebDrake** [comment]
Further note: my own benchmarking of this suggests that performance actually improves slightly if `_z` is removed entirely, and L153 is replaced by
```
auto z = data[index];
```

Happy to submit a patch with that solution if it would be acceptable.

**Comment by WebDrake** [comment]
> Further note: my own benchmarking of this suggests that performance actually improves slightly if `_z` is removed entirely

... with a side benefit being that `opCall` no longer needs to be called from the constructor.

**Comment by 9il** [comment]
> Presumably the intention/expectation is that _z should be initialized to data[index] in the constructor?

_z is not not `data[index]` it is `data[previous_index]`

**Comment by 9il** [comment]
> Further note: my own benchmarking of this suggests that performance actually improves slightly if _z is removed entirely, and L153 is replaced by

Please check checksums

**Comment by 9il** [comment]
The only reason to init _z is CTFE-able Mt, will init it with zero

**Comment by 9il** [comment]
Done https://github.com/libmir/mir-random/commit/5a5e66eb8e36ab11a40b6731c166bee67595a4ad
