### ISSUE TITLE
Time for mir-random 3.0?

### ISSUE THREAD

**Issue by n8sh** [libmir/mir-random#64]
With [Mir v0.7.0](https://github.com/libmir/mir-algorithm/releases/tag/v0.7.0) released with `extMul`, I think it may be time for a new mir-random release. Agree?

**Comment by 9il** [comment]
Yes

**Comment by n8sh** [comment]
v0.3.0 [forum](https://forum.dlang.org/post/eesziwkeivkxkrgluzom@forum.dlang.org) / [tag](https://github.com/libmir/mir-random/releases/tag/v0.3.0). Closing.
