### ISSUE TITLE
Design concerns for isRandomEngine template check

### ISSUE THREAD

**Issue by WebDrake** [libmir/mir-random#7]
`isRandomEngine` makes use of the `RandomEngine` UDA in order to determine if a given functor is a random engine or not.  Aside from terminology (technically a random _engine_ is a pseudo-random generator, and this check does not account for pseudo-random vs. 'true' random), there are a number of concerns with this approach:

* **Forced dependencies.**  The `isUniformRNG` check in Phobos' `std.random`, which looks for a compile-time boolean flag `isUniformRandom`, means that 3rd-party code can implement compatible generators without having any direct dependency on `std.random`.  For example, the code implemented at https://github.com/WebDrake/dxorshift does not import `std.random` except in unittests, where it is used to verify compatibility.  By contrast any code that wishes to implement `mir.random`-compatible RNGs is forced to import the `RandomEngine` enum.

* **Forwarding of information via generic wrappers.**  The UDA will not be available if a generator is wrapped by functionality like (say) `RefCounted` or `Unique`.  Currently enum constant fields will also not be forwarded (see: https://issues.dlang.org/show_bug.cgi?id=14830) but that at least seems possible in principle; it seems more dubious that UDAs would be reasonable to forward via a generic wrapper.

With this in mind it might be worth considering if a UDA is the right way to mark functors as random number generators.

**Comment by 9il** [comment]
> The UDA will not be available if a generator is wrapped by functionality like (say) RefCounted or Unique

Good point

**Comment by 9il** [comment]
https://github.com/libmir/mir-random/commit/d1bfb252060a5b734f8a92c07d05f6044e2a015a

**Comment by WebDrake** [comment]
Just to follow up briefly on your solution here -- you've used `isRandomEngine` as the name of your flag.  Do you intend to have distinct `isRandomEngine` and `isRandomDevice` flags for pseudo-random and 'true' random generators?

I would personally suggest just going for a general `isRandomGenerator` flag that covers both, but your call.
