### ISSUE TITLE
Vose's O(1) discrete random sampler

### ISSUE THREAD

**Issue by wilzbach** [libmir/mir-random#83]
There used to be Vose's O(1) discrete sampler in `mir`:

https://github.com/libmir/mir/pull/259
https://github.com/libmir/mir/blob/da76cf406d06957e472b9ba90b4c90b917480cb9/source/mir/random/discrete.d
Paper: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.398.3339&rep=rep1&type=pdf

It was pretty cool because it allowed fast sampling once the initial setup cost of O(n) is paid.

@9il: I assume that you didn't port it because of its usage of the experimental Allocator?
It could be changed to use malloc and either `@disable this(this)` or allow copying with ref-counting.

Q: Is there interest in porting this to mir-random and if so how would you like the allocation of the working data to be done?

**Comment by 9il** [comment]
An easy GC based API can be added for now. A bug fix for Issue 16486 will help to create RC ndslices)
