### ISSUE TITLE
Tiny Mersenne Twister

### ISSUE THREAD

**Issue by Ezneh** [libmir/mir-random#9]
This is an enhancement request concerning the Tiny Mersenne Twister algorithm :

As a request, could it be implemented / added to mir ?

Thanks,
Ezneh.

**Comment by 9il** [comment]
@Ezneh It can be added if someone implement it.

**Comment by n8sh** [comment]
@Ezneh For that niche I would suggest [xoroshiro128+](http://docs.random.dlang.io/latest/mir_random_engine_xorshift.html#Xoroshiro128Plus).

**Comment by n8sh** [comment]
The currently recommended replacement for the Tiny Mersenne Twister is [`xoshio256**`](http://docs.random.dlang.io/latest/mir_random_engine_xorshift.html#Xoshiro256StarStar) (64 bit oriented) or [`xoshio128**`](http://docs.random.dlang.io/latest/mir_random_engine_xorshift.html#Xoshiro128StarStar_32) (32 bit oriented). On top of having statistically superior output they are around 4x faster than TinyMT.
